---
sudo: required

services:
  - docker

before_install:
  # Fetch base image and build new container
  - sudo docker pull ubuntu:14.04
  - sudo docker build --rm=true --tag=ansiblepoc .

script:
  # Run container in detached state
  - python ansible-gen.py --input=bash_history.travis
  - sudo docker run -itd --privileged --name=ansiblecon --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ansiblepoc:latest
  - sudo docker images
  # Check syntax of ansible playbook
  - sudo docker exec -it ansiblecon ansible-playbook /etc/ansible/roles/role_under_test/ansible.yml --syntax-check
  - sudo docker exec -it ansiblecon ansible --version
  # Run ansible playbook
  - sudo docker exec -it ansiblecon ansible-playbook /etc/ansible/roles/role_under_test/ansible.yml

