---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=2.2.1.0

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-apt python3-apt python-apt-common

install:
  # Install Ansible.
  - pip install ansible

script:
  # Create ansible script.
  #- python ansible-gen.py --input=bash_history.travis
  
  # Execute ansible script
  - ansible-playbook  ansible.yml


