---
- environment:
    PWD: /home/ubuntu
  remote_user: ubuntu
  hosts: ec2
  name: Bash converted playbook
  tasks:
  - name: change directory
    set_fact:
      cwd: /home/ubuntu
  - sudo: 'yes'
    name: Run apt-get update
    apt:
      update_cache: 'yes'
  - sudo: 'yes'
    name: Run apt-get dist-upgrade
    apt:
      upgrade: dist
  - sudo: 'yes'
    name: Install package
    apt:
      name: '{{ item }}'
      state: present
    with_items:
    - python-pip
    - chromium-browser
    - chromium-chromedriver
  - sudo: 'no'
    name: Create directory
    file:
      path: /media/scraped
      state: directory
  - sudo: 'no'
    name: chown directory
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - shell: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
    sudo: 'no'
    name: echo
  - mount:
      path: /media/scraped
    sudo: 'no'
    name: Mount directory
  - sudo: 'no'
    name: chown directory
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - shell: cd {{ cwd }} && git clone git@github.com:mgajda/scraper-python.git
    sudo: 'no'
    name: Git clone
  - name: change directory
    set_fact:
      cwd: scraper-python
  - pip:
      requirements: '{{ cwd }}/requirment.txt'
    sudo: 'no'
    name: pip packages
  - sudo: 'no'
    name: Remove Directory
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - '{{ cwd }}/html'
    - '{{ cwd }}/logs'
    - '{{ cwd }}/output_csv'
