---
- connection: localhost
  environment:
    PWD: /home/ubuntu
  hosts: localhost
  name: Bash converted playbook
  remote_user: ubuntu
  tasks:
  - name: Set default working directory
    set_fact:
      cwd: /home/ubuntu
  - local_action: shell ls ansible/
    name: scp ansible/* ie-scraper:.ssh/
    register: key_file
    sudo: 'no'
  - copy:
      dest: '{{ cwd }}/.ssh//{{ item }}'
      src: ansible/{{ item }}
    with_items: '{{ key_file.stdout_lines }}'
  - apt:
      update_cache: 'yes'
    name: apt-get update;
    sudo: 'yes'
  - apt:
      upgrade: dist
    name: apt-get dist-upgrade -y;
    sudo: 'yes'
  - apt:
      name: '{{ item }}'
      state: present
    name: apt-get install -y python-pip chromium-browser chromium-chromedriver
    sudo: 'yes'
    with_items:
    - python-pip
    - chromium-browser
    - chromium-chromedriver
  - file:
      path: /media/scraped
      state: directory
    name: mkdir /media/scraped
    sudo: 'no'
  - file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
    name: chown ubuntu:ubuntu /media/scraped
    sudo: 'no'
  - name: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
    shell: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
    sudo: 'no'
  - mount:
      path: /media/scraped
    name: mount /media/scraped
    sudo: 'no'
  - file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
    name: chown -R ubuntu:ubuntu /media/scraped
    sudo: 'no'
  - name: git clone git@github.com:mgajda/scraper-python.git
    shell: cd {{ cwd }} && git clone git@github.com:mgajda/scraper-python.git
    sudo: 'no'
  - name: cd scraper-python
    set_fact:
      cwd: '{{ cwd }}/scraper-python'
    sudo: 'no'
  - name: pip install -r requirements.txt
    pip:
      requirements: '{{ cwd }}/requirment.txt'
    sudo: 'no'
  - file:
      path: '{{ item }}'
      state: absent
    name: rm -rf html logs output_csv
    sudo: 'no'
    with_items:
    - '{{ cwd }}/html'
    - '{{ cwd }}/logs'
    - '{{ cwd }}/output_csv'
