---
- name: Bash converted playbook
  hosts: ec2
  remote_user: ubuntu
  environment:
    PWD: /home/ubuntu
  tasks:
  - name: Set default working directory
    set_fact:
      cwd: /home/ubuntu
  - name: 'scp -r dockerProject targetHost:'
    sudo: 'no'
    copy:
      dest: '{{ cwd }}'
      src: dockerProject
  - name: cd dockerProject
    set_fact:
      cwd: dockerProject
  - name: sudo docker build -f Dockerfile-cpu -t ihaskell-nlp:latest .
    sudo: 'yes'
    docker_image:
      dockerfile: Dockerfile-cpu
      name: ihaskell-nlp
      path: '{{ cwd }}'
      tag: latest
