---
- name: Bash converted playbook
  connection: localhost
  hosts: localhost
  remote_user: ubuntu
  environment:
    PWD: /home/ubuntu
  tasks:
  - name: Set default working directory
    set_fact:
      cwd: /home/ubuntu
  - name: scp ansible/* ie-scraper:.ssh/
    sudo: 'no'
    local_action: shell ls ansible/
    register: key_file
  - copy:
      dest: '{{ cwd }}/.ssh//{{ item }}'
      src: ansible/{{ item }}
    with_items: '{{ key_file.stdout_lines }}'
  - name: sudo apt-get update;
    sudo: 'yes'
    apt:
      update_cache: 'yes'
  - name: sudo apt-get dist-upgrade -y;
    sudo: 'yes'
    apt:
      upgrade: dist
  - name: sudo apt-get install -y python-pip chromium-browser chromium-chromedriver
    sudo: 'yes'
    apt:
      name: '{{ item }}'
      state: present
    with_items:
    - python-pip
    - chromium-browser
    - chromium-chromedriver
  - name: mkdir /media/scraped
    sudo: 'no'
    file:
      path: /media/scraped
      state: directory
  - name: chown ubuntu:ubuntu /media/scraped
    sudo: 'no'
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - name: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
    sudo: 'no'
    shell: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
  - name: mount /media/scraped
    sudo: 'no'
    mount:
      path: /media/scraped
  - name: chown -R ubuntu:ubuntu /media/scraped
    sudo: 'no'
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - name: git clone git@github.com:mgajda/scraper-python.git
    sudo: 'no'
    shell: cd {{ cwd }} && git clone git@github.com:mgajda/scraper-python.git
  - name: cd scraper-python
    set_fact:
      cwd: '{{ cwd }}/scraper-python'
  - name: pip install -r requirements.txt
    sudo: 'no'
    pip:
      requirements: '{{ cwd }}/requirment.txt'
  - name: rm -rf html logs output_csv
    sudo: 'no'
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - '{{ cwd }}/html'
    - '{{ cwd }}/logs'
    - '{{ cwd }}/output_csv'
