---
- environment:
    PWD: /home/ubuntu
  sudo: 'yes'
  hosts: ec2
  name: Bash converted playbook
  remote_user: ubuntu
  tasks:
  - name: change directory
    set_fact:
      cwd: /home/ubuntu
  - name: Run apt-get update
    apt:
      update_cache: 'yes'
  - name: Run apt-get dist-upgrade
    apt:
      upgrade: dist
  - name: Install package
    apt:
      name: python-pip
      state: present
  - name: Install package
    apt:
      name: chromium-browser
      state: present
  - name: Install package
    apt:
      name: chromium-chromedriver
      state: present
  - name: Create directory
    file:
      path: /media/scraped
      state: directory
  - name: chown directory
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - shell: echo /dev/xvdp /media/scraped/ ext4 auto 0 1 >> /etc/fstab
    name: echo
  - mount:
      path: /media/scraped
    name: Mount directory
  - name: chown directory
    file:
      dest: /media/scraped
      group: ubuntu
      owner: ubuntu
      recurse: 'yes'
  - shell: cd {{ cwd }} && git clone git@github.com:mgajda/scraper-python.git
    name: Git clone
  - name: change directory
    set_fact:
      cwd: scraper-python
  - pip:
      requirements: '{{ cwd }}/requirment.txt'
    name: pip packages
  - name: rm dir
    file:
      path: '{{ cwd }}/html'
      state: absent
  - name: rm dir
    file:
      path: '{{ cwd }}/logs'
      state: absent
  - name: rm dir
    file:
      path: '{{ cwd }}/output_csv'
      state: absent
