- gather_facts: false
  hosts: localhost
  connection: local
  name: Create new instance according to ec2_config.yml
  tasks:
  - include_vars:
      file: ec2_config.yml
  - ec2:
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: yes
      count: 1
      instance_tags:
        Name: scrapper
      region: "{{ region }}"
    register: ec2

  - name: Add all instance public IPs to host group
    add_host: hostname={{ item.public_ip }} groups=ec2hosts
    with_items: "{{ ec2.instances }}"

  - name: Wait for the instances to boot by checking the ssh port, check by ip
    wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
    with_items: "{{ ec2.instances }}"
